config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_bash_profile:
    src: bash_profile
    dst: ~/.bash_profile
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_gitignore:
    src: gitignore
    dst: ~/.gitignore
  f_init.vim:
    src: config/nvim/init.vim
    dst: ~/.config/nvim/init.vim
profiles:
  moria:
    dotfiles:
    - f_bash_profile
    - f_bashrc
    - f_tmux.conf
    - f_gitconfig
    - f_gitignore
    - f_init.vim
